Remapper environment and level
ericdanielfb/CentralDeErros pull request #10
Opened 2020-07-21 02:47 UTC by Marcelojr61

2020-07-21 02:53 UTC, ericdanielfb requested changes

2020-07-21 02:53 UTC, ericdanielfb commented on CentralDeErros.Data/Maps/MicrosserviceMap.cs
> +                .ToTable("microservice");
Mano, ficou faltando um S em 'microsservice'

2020-07-21 02:53 UTC, ericdanielfb commented on CentralDeErros.Data/Maps/PerfilMap.cs
>          public void Configure(EntityTypeBuilder<Perfil> builder)
Reparando agora, acho que pisamos na bola. Tá tudo em inglês, exceto o 'Perfil'. Deveria ser 'Profile', concordam?

@Marcelojr61 @Kendov @MarceloAmorim25

2020-07-21 03:01 UTC, Marcelojr61 commented on CentralDeErros.Data/Maps/PerfilMap.cs
>          public void Configure(EntityTypeBuilder<Perfil> builder)
Vdd.

2020-07-21 15:35 UTC, Kendov commented on CentralDeErros.Data/Maps/PerfilMap.cs
>          public void Configure(EntityTypeBuilder<Perfil> builder)
É mesmo. Não tinha percebido isso.

2020-07-22 01:15 UTC, marcelomamorim submitted a review, later dismissed

2020-07-22 02:34 UTC, ericdanielfb approved these changes

2020-07-22 03:00 UTC, ericdanielfb approved these changes

2020-07-22 03:02 UTC, Kendov approved these changes

2020-07-22 03:02 UTC, merged