Feat/user services
ericdanielfb/CentralDeErros pull request #20
Opened 2020-08-04 05:53 UTC by MarceloAmorim25

Adiciona UserServices, as configurações do AutoMapper e o UserDTO

2020-08-05 00:55 UTC, Marcelojr61 requested changes

2020-08-05 00:55 UTC, Marcelojr61 commented on CentralDeErros.Transport/UserDTO.cs
> +        public string Password { get; set; }
A DTO deve conter apenas o que é importante o front receber, nessa caso não prudente devolver todos os dados do banco, talvez faça sentido devolver apenas UserName e Email ou até apenas um dos dois.

2020-08-07 00:22 UTC, Kendov submitted a review, later dismissed

2020-08-07 15:39 UTC, Kendov approved these changes

2020-08-07 15:39 UTC, Marcelojr61 approved these changes

2020-08-07 15:40 UTC, merged