Readme
ericdanielfb/CentralDeErros pull request #27
Opened 2020-08-09 10:40 UTC by MarceloAmorim25

Atualiza o README - template Wiz

2020-08-09 19:01 UTC, Marcelojr61 approved these changes

2020-08-10 00:46 UTC, Kendov approved these changes

2020-08-10 01:17 UTC, Marcelojr61 requested changes

2020-08-10 01:17 UTC, Marcelojr61 commented on CentralDeErros.API/Controllers/UserController.cs
> +        public ActionResult<UserDTO> Update(int id) => Ok(mapper.Map<UserDTO>(service.Fetch(id)));
Marcelão, aqui ainda está da mesma forma que branch da UserController, antes da correção. 

Um ponto que vimos depois que fizermos o Pull da dev atualizada é que ao usar o mapper no método void ele acusa erro de argumento, assim deixo uma opção de solução aqui abaixo. 


        [HttpPut("{id}")]
        public ActionResult<UserDTO> Update(User user) 
        {
           if(ModelState.IsValid)
           {
                service.Update(user);
                return Ok();
           }

           return NotFound();

2020-08-10 01:40 UTC, MarceloAmorim25 commented on CentralDeErros.API/Controllers/UserController.cs
> +        public ActionResult<UserDTO> Update(int id) => Ok(mapper.Map<UserDTO>(service.Fetch(id)));
Já tá assim lá, Marcelo! A branch que eu alterei foi a user-controller, não comitei as mudanças na branch do readme, dá uma olhada lá na branch dev, tá alterado!

2020-08-10 01:45 UTC, Marcelojr61 approved these changes

2020-08-10 01:45 UTC, merged