Feat/model tests fix
ericdanielfb/CentralDeErros pull request #34
Opened 2020-08-11 01:46 UTC by MarceloAmorim25

Refatora as controllers e retorna NoContent ao invés de exceptions.

Refatora os testes das Models.

2020-08-11 15:23 UTC, Kendov submitted a review, later dismissed

2020-08-11 21:40 UTC, Marcelojr61 requested changes

2020-08-11 21:40 UTC, Marcelojr61 commented on CentralDeErros.API/Controllers/ProfileController.cs
> +            return NotContent();
Marcelão depois dá uma olhada no que houve aqui pq não entendemos, o retorno 204 é NoContent();

2020-08-11 21:57 UTC, MarceloAmorim25 commented on CentralDeErros.API/Controllers/ProfileController.cs
> +            return NotContent();
Ops! Foi falha de digitação mesmo! Valeu pelo review, Marcelo!

2020-08-15 01:06 UTC, ericdanielfb commented on CentralDeErros.API/Controllers/ProfileController.cs
> +            return NotContent();
Corrigido

2020-08-15 01:07 UTC, Kendov approved these changes

2020-08-15 01:09 UTC, Marcelojr61 approved these changes

2020-08-15 01:09 UTC, merged